# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e3d0e81bbd4b5db5934ba297d780bb6ba81f3e3798c14129de7bc62c623044f3b7db7ba4400b8d2ef3e805627d1049e899b8cdf2631fc32102a7b75f1bb3e2f

test:
  secret_key_base: 62d44369101aafae0473601755e6111c65d30e0e2327a26041b6ac39450ce243135d4b04538a0c83144e9ab75713336ea45541586f1fe1ee30efa4fa37a765f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
